# ==============================================================================
# OPENER DEFINITIONS
# ==============================================================================
[opener]
edit = [
	{ run = 'zeditor --wait "$@"', block = true, desc = "Zed" }
]

view = [
	{ run = 'qimgv "$@"', orphan = true, desc = "qimgv" }
]

play = [
	{ run = 'mpv "$@"', orphan = true, desc = "qimgv" }
]

docs = [
	{ run = 'zathura "$@"', orphan = true, desc = "Zathura" }
]

[open]
prepend_rules = [
	# dirs (opens a whole folder in zed with O)
	{ name = "*/", use = [ "edit", "open" ] },

	{ name = "*.nix", use = "edit" },
	{ mime = "text/*", use = "edit" },
	{ mime = "application/{json,javascript,x-shellscript}", use = "edit" },
	{ name = "*.{yml,yaml,toml,conf,sh,py,lua,md,csv,rs,go,c,cpp,h}", use = "edit" },

	{ mime = "image/*", use = "view" },
	{ name = "*.svg", use = "view" },

	{ mime = "{video,audio}/*", use = "play" },

	{ mime = "application/pdf", use = "docs" },
	{ name = "*.{docx,xlsx,pptx}", use = "docs" },
]
