# Gruvbox Material Dark Hard (Sainnhe Park)

"ui.background" = { bg = "#1d2021" }
"ui.text" = "#d4be98"
"ui.cursor" = { fg = "#1d2021", bg = "#a89984" }
"ui.selection" = { bg = "#504945" }
"ui.statusline" = { fg = "#d4be98", bg = "#282828" }
"ui.window" = { fg = "#32302f" }
"ui.help" = { bg = "#282828", fg = "#d4be98" }
"ui.linenr" = { fg = "#665c54" }
"ui.linenr.selected" = { fg = "#d4be98" }
"ui.popup" = { bg = "#282828" }
"ui.menu" = { fg = "#d4be98", bg = "#282828" }
"ui.menu.selected" = { fg = "#1d2021", bg = "#a9b665" }

"keyword" = "#ea6962"
"variable" = "#d4be98"
"variable.builtin" = "#89b482"
"constant" = "#d3869b"
"function" = "#a9b665"
"string" = "#a9b665"
"comment" = { fg = "#928374", modifiers = ["italic"] }
"type" = "#d8a657"
"operator" = "#e78a4e"
"attribute" = "#89b482"
"constructor" = "#d8a657"
"special" = "#e78a4e"

"error" = "#ea6962"
"warning" = "#e78a4e"
"info" = "#7daea3"
"hint" = "#89b482"

"diagnostic.error" = { underline = { color = "#ea6962", style = "curl" } }
"diagnostic.warning" = { underline = { color = "#e78a4e", style = "curl" } }

"markup.heading" = "#d3869b"
"markup.list" = "#ea6962"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "#7daea3", modifiers = ["underline"] }
"markup.link.text" = "#ea6962"
